name: deploy-detection
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
    - shell: bash
      run: |
        cd /home/splunker
        source .venv/bin/activate
        mkdir app_v3
        cd app_v3
        contentctl init
        contentctl build
        scp -r dist/ContentPack splunk@10.202.20.205:/opt/splunk/etc/apps
        ssh -t splunk@10.202.20.205 '/opt/splunk/bin/splunk restart'
