name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
    - shell: bash
      run: |
        cd /home/splunker
        source .venv/bin/activate
        contentctl validate
        
