name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
    - shell: bash
      run: |
        cd /home/splunker
        source .venv/bin/activate
        git clone https://github.com/splunk/security_content.git
        cd security_content
        contentctl build
        scp -r dist/DA-ESS-ContentUpdate splunk@10.202.20.205:/opt/splunk/etc/apps
        ssh -t splunk@10.202.20.205 'whoami'
